### ISSUE TITLE
[FR] Project Examples for PlatformIO Registry

### ISSUE THREAD

**Issue by qouoww** [BOJIT/PlatformIO-FreeRTOS#2]
Hi,

Currently, the [library page](https://registry.platformio.org/libraries/bojit/PlatformIO-FreeRTOS) in the PlatformIO Registry doesn't contain any quick start projects for developers. Such examples serve both to highlight widespread use cases and to help newcomers to get up and running much more quickly.

Please consider adding a few comprehensive project examples to the PlatformIO Registry.

Useful links:
- https://registry.platformio.org/libraries/bojit/PlatformIO-FreeRTOS
- https://docs.platformio.org/en/latest/librarymanager/config.html#examples

**Comment by BOJIT** [comment]
Hi,

Some examples would be a good idea - currently I haven't got any good small examples of how to use this library. I'll consider adding them in the near future. However this library is just a wrapper for the FreeRTOS-Kernel, so docs about how to use FreeRTOS don't really belong in this page.

An example of the library usage is shown here: https://github.com/Open-AES67/PTP-GM/blob/master/platformio.ini

What platform are you targeting? I can give some advice in the short-term if need be.

Cheers
